### ISSUE TITLE
Specifying Debian as OS does not work

### ISSUE THREAD

**Issue by renegat59** [newrelic/infrastructure-agent-ansible#18]
I was following the README file and it claims, that we can take the OS version from meta/main.yml. There it says we can use Ubuntu with one of three versions:
- precise
- trusty
- xenial

This doesn't work, and when checking the code I see that it's never checked. The only OS checked are redhat and debian. Maybe the README should be changed so it's not misleading?

**Comment by fideloper** [comment]
Hi!

You can see those set in the [`vars/main.yml`](https://github.com/newrelic/infrastructure-agent-ansible/blob/master/vars/main.yml) file and use Ansible core variables to set the custom variables they setup.

Note that `ansible_os_family` sets the OS family and will return `debian` **even** on Ubuntu servers, since Ubuntu is downstream from Debian.

This should Just Work™ on Ubuntu servers as well - those vars will get set automatically.

**Comment by smith** [comment]
I've been able to successfully use this on all versions mentioned. I'm going to close this, but if you think it should be reopened, please do so and post a link to some console output from the failure so we can see what's happening.
