### ISSUE TITLE
Unable to start agent because log file isn't created

### ISSUE THREAD

**Issue by popopanda** [newrelic/infrastructure-agent-ansible#33]
Hello,

Specifying a log_file variable such as `log_file: /var/log/newrelic/nr-infra.log` does not create the log file in `/var/log/newrelic/nr-infra.log`. As a result, the agent is unable to start since it fails to write to the log file

**Comment by xino12** [comment]
Hello @popopanda this is probably because the directory /var/log/newrelic/ directory does not exists.
If you want to log to a subdirectory inside /var/log you should ensure that that subdirectory is created.
You can add an additional step in the tasks like this:

`
- name: Create /var/log/newrelic directory
   file:
     path: /var/log/newrelic
     state: directory
     mode: 0755`

With this extra step you will be able to setup the agent to log in a subdirectory inside /var/log

Another solution would be to setup to log to /var/log/nr-infra.log.

Hope this helps.

**Comment by popopanda** [comment]
Thank you for the suggestion, changing it to ` /var/log/nr-infra.log` works as intended

Thanks!
