### ISSUE TITLE
Task "run make cache to actually import gpg key" fails on RHEL8

### ISSUE THREAD

**Issue by Mireiawen** [newrelic/infrastructure-agent-ansible#82]
Hi!
When running on the role on a RHEL8 Vagrant box, box being generic/rhel8, I am getting the following error:

```
TASK [newrelic.newrelic-infra : run make cache to actually import gpg key] *****
fatal: [local_db_master]: FAILED! => {"changed": true, "cmd": ["yum", "-q", "makecache", "-y", "--disablerepo=*", "--enablerepo=newrelic-infra"], "delta": "0:00:03.550867", "end": "2020-04-14 09:20:13.197761", "msg": "non-zero return code", "rc": -13, "start": "2020-04-14 09:20:09.646894", "stderr": "Importing GPG key 0x8ECCE87C:\n Userid     : \"infrastructure-eng <infrastructure-eng@newrelic.com>\"\n Fingerprint: A758 B3FB CD43 BE8D 123A 3476 BB29 EE03 8ECC E87C\n From       : https://download.newrelic.com/infrastructure_agent/gpg/newrelic-infra.gpg", "stderr_lines": ["Importing GPG key 0x8ECCE87C:", " Userid     : \"infrastructure-eng <infrastructure-eng@newrelic.com>\"", " Fingerprint: A758 B3FB CD43 BE8D 123A 3476 BB29 EE03 8ECC E87C", " From       : https://download.newrelic.com/infrastructure_agent/gpg/newrelic-infra.gpg"], "stdout": "", "stdout_lines": []}
```

If I add `failed_when: false` to the task, it works fine.

**Comment by JakubKotkowiak** [comment]
Hello @Mireiawen, thank you for reporting the issue. Is it still relevant? If so could you please provide some more information like the ansible version used on this failing job as well as what command did you use to run it and how did your snippet to install the newrelic role looked like? At a first glance it looks like permission issue since I receive a similar error when running the command in question without the necessary permissions. Thanks in advance!

**Comment by JakubKotkowiak** [comment]
Closing this issue due to a lack of activity.
